config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get 'comments/create'
  get 'comments/destroy'
  root 'pictures#index'
  get '/login', to: 'sessions#new'
  get '/search', to: 'pictures#search'
#  get '/users/:id/follower', to: 'users#follower'
  resources :notifications, only: :index

  resources :pictures do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
    resource :favorites, only: [:create, :destroy]
    get :favorites, on: :member
  end


end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :picture
  validates :content, presence: true, length: { maximum: 100 }


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
#before_action :require_user_logged_in?

  def create
    @pic = Picture.find(params[:picture_id])
    @comment = @pic.comments.build(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      flash[:success] = "投稿にコメントしました"
      #投稿時ページトップに遷移してしまう
      #render :index
      #通知
      @picture = Picture.find(params[:picture_id])
      @picture.create_notification_comment!(current_user)
      redirect_to picture_path(params[:picture_id])
    else
      flash.now[:danger] = '投稿へのコメントに失敗しました。'
      #削除時ページトップに遷移してしまう
      render :index
      #redirect_to picture_path(params[:picture_id])
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      #render :index
      redirect_to picture_path(params[:picture_id])
    end
  end


  private

  def comment_params
    #params.require(:comment).permit(:content, :picture_id, :user_id)
    params.require(:comment).permit(:content, :picture_id)
  end

end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: [pic, comment]) do |f| %>
  <%= f.text_area :content, class: 'form-control' %>
  <%= f.submit 'Comment', class: 'btn btn-primary btn-block' %>
<% end %>

app/views/comments/_index.html.erb
<% comments.each do |comment| %>
  
  <%= link_to "#{comment.user.name}: ", user_path(comment.user.id) %>
  <%= comment.content %>
  <%= link_to "Delete", picture_comment_path(comment.picture_id, comment.id), method: :delete, remote: true, class: 'btn btn-danger btn-sm' %>　<br> <br>
<% end %>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'index', { comments: @comment.picture.comments }) %>")
$("textarea").val('')