config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get 'comments/create'
  get 'comments/destroy'
  root 'pictures#index'
  get '/login', to: 'sessions#new'
  get '/search', to: 'pictures#search'
#  get '/users/:id/follower', to: 'users#follower'
  resources :notifications, only: :index

  resources :pictures do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
    resource :favorites, only: [:create, :destroy]
    get :favorites, on: :member
  end


end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :image
  mount_uploader :image, ImageUploader
  has_many :pictures, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorite_pictures, through: :favorites, source: :picture

  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower

  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

  def create_notification_follow!(current_user)
    notification = current_user.active_notifications.new(
      visited_id: self.id,
      action: "follow"
    )
    notification.save if notification.valid?
  end

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        email:    auth.info.email,
        name:  auth.info.name,
        password: Devise.friendly_token[0, 20],
        image:  auth.info.image
      )
    end

    user
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_from :facebook
  end

  private

  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :favorites, :edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  # GET /users
  # GET /users.json
  def index
    @title = "ユーザー一覧"
    @users = User.all
    @pic = current_user.pictures.build
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @pictures = @user.pictures
    @favorite_pictures = @user.favorite_pictures
  end
  def favorites
    @favorite_pictures = @user.favorite_pictures
    @pictures = @user.favorite_pictures
    render 'users/show'
  end
  # GET /users/new
  def new
    @user = User.new
  end
  # GET /users/1/edit
  def edit
  end
    
  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.image.attach(params[:user][:image])
    @user.image = "default.png"
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if @user.update(user_params)
      flash[:success] ="your account was updated"
      #redirect_to root_path
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def follows
    @title = "Follows"
    user = User.find(params[:id])
    @users = user.followings
    render 'index'
  end

  def followers
    @title = "Followers"
    user = User.find(params[:id])
    @users = user.followers
    render 'index'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:image, :username, :name, :email, :link, :profile, :sex, :tel)
    end

    def require_same_user
      if current_user != @user and !current_user.admin?
        flash[:dander] = "他人のアカウントに茶々入れたらダメだよ"
        redirect_to root_path
      end
    end
    def require_admin
      if logged_in? and !current_user.admin?
        flash[:dander] = "管理者しかできないアクションだよ"
        redirect_to root_path
      end
    end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

app/views/users/_profile.html.erb
<%= render 'users/user_image', obj: @user %><br>
<%= render 'relationships/follow'%> <br>
<% if user_signed_in? && current_user == @user %>
  <%= link_to "プロフィールを充実させる",edit_user_path(current_user) %>
  <%= link_to "情報変更", edit_user_registration_path %> <br>
<% end %>
<%= link_to "フォロー中[#{@user.active_relationships.count}]", follows_user_path %>|
<%= link_to "フォロワー[#{@user.passive_relationships.count}]", followers_user_path %> <br>
<%= link_to "本人の投稿[#{@user.pictures.count}]", user_path %>|
<%= link_to "お気に入りした投稿[#{@user.favorite_pictures.count}]", favorites_user_path %><br>
<%=  "username: #{@user.username}<br>".html_safe if @user.username? %>
<%=  "name: #{@user.name}<br>".html_safe if @user.name? %> 
<%=  "link: #{@user.link}<br>".html_safe if @user.link? %>
<%=  "性別: #{@user.sex}<br>".html_safe if @user.sex?%>
<%=  "profile: #{@user.profile}<br>".html_safe if @user.profile? %> <br>

app/views/users/_user_image.html.erb
  <% if obj.image? %>
    <%= link_to image_tag(obj.image.url, class:"resize2"), obj %>
  <% else %>
    <%= link_to image_tag("/assets/default.png", class:"resize2"), obj %>
  <% end %>

app/views/users/edit.html.erb
edit

<%= form_for(@user, :html => {class: "form-horizontal", role:"form"}) do |f| %>
  <div class="picture">
    <%= f.file_field :image %> <br>
  </div>
  <%= f.label :username %>
  <%= f.text_field :username, class: "float form-control", placeholder: "user name",autofocus: true %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "float form-control" %>

  <%= f.label :profile %>
  <%= f.text_area :profile, class: "float form-control" %>

  <%= f.label :link %>
  <%= f.text_field :link, class: "float form-control" %>

  <%= f.label :tel %>
  <%= f.text_field :tel, class: "float form-control" %>

  <%= f.label :性別 %>
  <label><%= f.radio_button :sex, "男  " %> 男  </label>
  <label><%= f.radio_button :sex, "女  " %> 女  </label>
  <label><%= f.radio_button :sex, "無回答" %> 無回答  </label> <br>

  <%= f.label :email %>
  <%= f.email_field :email, class: "form-control", placeholder:"enter email" %>


  <%= f.submit "更新完了" , class:'btn btn-primary btn-lg'%>

<% end %>

<div align="center">
  [<%= link_to "戻る", root_path %>]
</div>

app/views/users/index.html.erb
<% provide(:title, "ユーザー一覧")%>
<div class="color2">
  <table>
      <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.name, user %></td>
          <% if current_user.admin? %>
            <td><%= link_to 'Edit', edit_user_path(user) %></td>
            <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name)%>
<div class="container">
  <div class="row">
    <div class="col-4 color1">
      <div class="fixed">
        <%= render 'users/profile' %>
      </div>
    </div>
    <div class="col-8 color2 main">
      <%= render 'pictures/picture', obj: @pictures %>
    </div>
  </div>
</div>