config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get 'comments/create'
  get 'comments/destroy'
  root 'pictures#index'
  get '/login', to: 'sessions#new'
  get '/search', to: 'pictures#search'
#  get '/users/:id/follower', to: 'users#follower'
  resources :notifications, only: :index

  resources :pictures do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
    resource :favorites, only: [:create, :destroy]
    get :favorites, on: :member
  end


end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :commenters, through: :commments, source: :user
  has_many_attached :image
  mount_uploader :image, ImageUploader
  validates :image, presence: true
  validates :title, presence: true
  validate  :image_size

  has_many :notifications, dependent: :destroy

  def self.search(search)
    return Picture.all unless search
    Picture.where(['title LIKE ?', "%#{search}"])
  end

  def create_notification_favorite!(current_user)
    notification = current_user.active_notifications.new(
      picture_id:self.id,
      visited_id:self.user.id,
      action:"favorite"
    )
    notification.save if notification.valid?
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def create_notification_comment!(current_user)
    notification = current_user.active_notifications.new(
      picture_id:self.id,
     # comment_id: comment_id,
      visited_id:self.user.id,
      action: "comment"
    )
    notification.save if notification.valid?
  end
  
  private
    # アップロードされた画像のサイズをバリデーションする
    def image_size
      if image.size > 5.megabytes
        errors.add(:image, "should be less than 5MB")
      end
    end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
before_action :find_pic, only: [:show, :edit, :update, :destroy, :upvote]
before_action :authenticate_user!, except: [:index, :show]
before_action :correct_user, only: :destroy
before_action :require_same_user, only: [:edit, :update, :destroy]
before_action :require_admin, only: [:destroy]

  def search
    if user_signed_in?
      @pic = current_user.pictures.build
    end
      @pics = Picture.search(params[:search])
  end

  def index
    if user_signed_in?
      @pic = current_user.pictures.build
      @users = current_user && current_user.followings
    else
      @users = User.all
    end
  end

  def create
    @pic_new = current_user.pictures.build(pic_params)
    if @pic_new.save
      redirect_to @pic_new, notice: "投稿されました"
    else
      render 'index'
    end
  end

  def show
    @comment = Comment.new
    @comments = @pic.comments 
  end

  def update
    if @pic.update(pic_params)
      redirect_to @pic, notice: "編集が完了しました"
    else
      render 'edit'
    end
  end

  def destroy
    if @pic.destroy
      redirect_to root_path
    end
  end

  private
  def pic_params
    params.require(:picture).permit(:title, :description, :image)
  end

  def find_pic
    @pic = Picture.find(params[:id])
  end

  def correct_user
    @pic = current_user.pictures.find_by(id: params[:id])
    redirect_to root_url if @pic.nil?
  end

  def require_same_user
    if current_user != @user and !current_user.admin?
      flash[:dander] = "他人の投稿に茶々入れたらダメだよ"
      redirect_to root_path
    end
  end
  def require_admin
    if logged_in? and !current_user.admin?
      flash[:dander] = "管理者しかできないアクションだよ"
      redirect_to root_path
    end
  end
end

app/helpers/pictures_helper.rb
# frozen_string_literal: true

module PicturesHelper
end

app/views/pictures/_fav_picture.html.erb
<% obj.each do |pic| %>
  <hr>
  <%= image_tag(pic.image.url, class:"resize") if pic.image? %> <br>
  <%=link_to pic.title, picture_path(pic.id) %>

<% end %>

app/views/pictures/_form.html.erb
<h3>投稿</h3>
<%= form_for(@pic) do |f| %>
  <div class="form-group">
    <%= f.file_field :image %>
  </div>
  <div class="form-group">
    <%= f.text_field :title, placeholder: "Title" %>
  </div>
  <div class="form-group">
    <%= f.text_area :description, placeholder: "説明" %>
  </div>
  <%= f.submit "送信" %>
<% end %>

<script type="text/javascript">
  $('#picture_image').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if(size_in_megabytes > 5){
      alert('5MB以下の写真をアップロードして下さい')
    }
  });
</script>

app/views/pictures/_picture.html.erb
<% obj.each do |pic| %>
  <%= link_to picture_path(pic) do %>
    <%= image_tag(pic.image.url, class:"resize") %>
    <h3><%= pic.title %>
    <% if pic.favorites.count > 0 %>
      <i class="fa fa-heart" style="color:red;"></i>
    <% else %>
      <i class="fa fa-heart-o" style="color:red;"></i>
    <% end %>
    </h3>
  <% end %>
<% end %>

app/views/pictures/_search.html.erb
<%= form_tag(search_path, :method =>'get') do %>
  <%= text_field_tag :search %>
  <%= submit_tag 'Search', :title => nil %>
<% end %>
<%= render 'picture', obj: @pics %>

app/views/pictures/edit.html.erb
<div class="color2">
  <h1>編集する</h1>
  <%= render '/pictures/form' %>
  <%= link_to "戻る", picture_path %>
</div>

app/views/pictures/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-4 color1 side">
      <% if user_signed_in? %>
        <% provide(:title, current_user.name)%>
        <div class="top-picture">
          <%= render 'users/user_image', obj: current_user %><br>
          <h1><%= current_user.name %></h1>
        </div>
        <div class="index">
          <% current_user.followings.each do |user| %>
            <%= render 'users/user_image', obj: user %>
          <% end %>
        </div>
        <div class="color2 form">
          <%= render 'pictures/form'%>
        </div>
      <% else %>
        <div class="fixed">
          <button type="button" class="btn btn-outline-primary"><%= link_to "新規登録", new_user_registration_path %></button>
          <button type="button" class="btn btn-outline-primary"><%= link_to "LogIn", new_user_session_path %></button><br><br>
          <button type="button" class="btn btn-outline-primary"><%= link_to "FBからログイン", user_facebook_omniauth_callback_path %></button>
        </div>
      <% end %>
    </div>
    <div class="col-8 color2 main">
      <% @users.each do |user| %>
        <% pics = Picture.where(user_id: user.id) %>
        <%= render 'picture', obj: pics %>
      <% end %>
    </div>
  </div>
</div>

app/views/pictures/search.html.erb
<% provide(:title, "検索")%>
<div class="container">
  <div class="row">
    <div class="col-4 color1 side">
      <h1><%= render 'users/user_image', obj: current_user %><br>
      <%= current_user.name %></h1><br>
      <div class="index">
        <% current_user.followings.each do |user| %>
          <%= render 'users/user_image', obj: user %>
        <% end %>
      </div>
      <div class="color2 form">
        <%= render 'pictures/form'%>
      </div>
    </div>
    <div class="col-8 color2 main">
      <%= render 'pictures/search', obj: @pics %>
    </div>
  </div>
</div>

app/views/pictures/show.html 2.erb
<div class="main color2">
  <%= image_tag @pic.image.url if @pic.image? %>
  <h1><%= @pic.title %></h1>
  <p><%= @pic.description %></p>
  <% if user_signed_in? %>
    <% if @pic.favorited_by?(current_user) %>
      <%=link_to picture_favorites_path(@pic.id), method: :delete do %>
        <i class="fa fa-heart fa-2x" style="color:red;"></i>
      <% end %>
    <% else %>
      <%=link_to picture_favorites_path(@pic.id), method: :post do %>
        <i class="fa fa-heart-o fa-2x" style="color:red;"></i>
      <% end %>
    <% end %>
  <% end %>
  <% if current_user == @pic.user %>
    <%= @pic.favorites.count %>
  <% end %>
  <div class="container">
    <div id="comments_area">
      <%= render partial: 'comments/index', locals: { comments: @comments } %>
    </div>
    <div class="comment_area">
      <%= render partial: 'comments/form', locals: { comment: @comment, pic: @pic }  %>
    </div>
  </div>
  Pic by
  <p><%= link_to @pic.user.name, user_path(@pic.user) %></p>
  <%= link_to "戻る", root_path %>
  <% if user_signed_in? && (current_user == @pic.user || current_user.admin?) %>
    <%= link_to "編集", edit_picture_path %>
    <%= link_to "消去", picture_path, method: :delete, data: {confirm: "本当によろしいですか？"} %>
  <% end %>
</div>

app/views/pictures/show.html.erb
<div class="main color2">
  <%= image_tag @pic.image.url if @pic.image? %>
  <h3><%= @pic.title %></h3>
  <h5><%= @pic.description %></h5>
  <% if user_signed_in? %>
    <% if @pic.favorited_by?(current_user) %>
      <%=link_to picture_favorites_path(@pic.id), method: :delete do %>
        <i class="fa fa-heart fa-2x" style="color:red;"></i>
      <% end %>
    <% else %>
      <%=link_to picture_favorites_path(@pic.id), method: :post do %>
        <i class="fa fa-heart-o fa-2x" style="color:red;"></i>
      <% end %>
    <% end %>
  <% end %>
  <% if current_user == @pic.user %>
    <%= @pic.favorites.count %>
  <% end %>
  <div class="container">
    <div id="comments_area">
      <%= render partial: 'comments/index', locals: { comments: @comments } %>
    </div>
    <div class="comment_area">
      <%= render partial: 'comments/form', locals: { comment: @comment, pic: @pic }  %>
    </div>
  </div>
  Pic by: <%= link_to @pic.user.name, user_path(@pic.user) %><br>
  <%= link_to "戻る", root_path %>
  <% if user_signed_in? && (current_user == @pic.user || current_user.admin?) %>
    <%= link_to "編集", edit_picture_path %>
    <%= link_to "消去", picture_path, method: :delete, data: {confirm: "本当によろしいですか？"} %>
  <% end %>
</div>

app/views/pictures/show.js.erb
$("#picture-modal").html("<%= escape_javascript(render(partial: 'show')) %>")
$("#picture-modal").modal("show")