config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get 'comments/create'
  get 'comments/destroy'
  root 'pictures#index'
  get '/login', to: 'sessions#new'
  get '/search', to: 'pictures#search'
#  get '/users/:id/follower', to: 'users#follower'
  resources :notifications, only: :index

  resources :pictures do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
    resource :favorites, only: [:create, :destroy]
    get :favorites, on: :member
  end


end

app/views/layouts/_footer.html 2.erb
<div class="footer">
  <p>Copyright hisakado motoki</p>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
  <p>Copyright hisakado motoki</p>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message_content| %>
  <div class="ui <%= message_type %> message transition">
    <i class="close icon"></i>
    <div class="header color">
      <%= message_content %>
    </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar ">
  <h1><a class="navbar-brand"><%= link_to "Instagram", root_path %></a></h1>
 <div align="right">
    <% if user_signed_in? %>
      <ul class="icons">
        <li><%= link_to search_path do %>
          <i class="fa fa-search fa-2x"></i>  
        <% end %></li>
        <li><%= link_to users_path do %>
          <i class="fa fa-users fa-2x"></i></i>  
        <% end %></li>
        <li><%= link_to user_path(current_user) do %>
          <i class="fa fa-user fa-2x" ></i>  
        <% end %></li>
        <li><%= link_to notifications_path do %>
          <i class="fa fa-bell-o fa-2x"></i>
        <% end %></li>
      </ul>
      <%= link_to "サインアウト", destroy_user_session_path, method: :delete %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
  </head>
  <body>
    <%= render 'layouts/navigation'  %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <script src="script.js"></script>
  </body>
</html>